version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/db
      REDIS: 'redis'
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db

  admin:
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080

  redis:
    image: "redis:alpine"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
     - "6379:6379"

    environment:
      REDIS_REPLICATION_MOD: master
